/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "stm32f407xx.h"
#include <string.h>

//Command Codes
#define COMMAND_LED_CTRL		0x50
#define COMMAND_SENSOR_READ		0x51
#define COMMAND_PIN_READ		0x52
#define	COMMAND_PRINT			0x53
#define	COMMAND_ID_READ			0x54

#define LED_ON		1
#define LED_OFF		0

#define ANALOG_PIN0		0
#define ANALOG_PIN1		1
#define ANALOG_PIN2		2
#define ANALOG_PIN3		3
#define ANALOG_PIN4		4

#define	LED_PIN 	3

/*
*This global variable used as a control bit for EXTI0 interrupt occur or not
*/
uint8_t Btn = RESET;

void Delay(uint32_t counter)
{
	for(uint32_t i =0 ; i<counter ; i++);
}

void SPI2_GPIO_Init()
{
	/*
	 * PB12 SPI2_NSS
	 * PB13 SPI2_SCK
	 * PB14 SPI2_MISO
	 * PB15 SPI2_MOSI
	 */

	GPIO_Handle_t GPIO_SPI;

	GPIO_SPI.pGPIOx = GPIOB;

	GPIO_SPI.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_AF;
	GPIO_SPI.GPIO_PinConfig.GPIO_PinAltFunMode = 5;
	GPIO_SPI.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GPIO_SPI.GPIO_PinConfig.GPIO_PuPdControl = GPIO_PIN_PU;
	GPIO_SPI.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OP_SPEED_HIGH;

	//NSS
	GPIO_SPI.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GPIO_Init(&GPIO_SPI);

	//SCL
	GPIO_SPI.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIO_Init(&GPIO_SPI);

	//MISO
	GPIO_SPI.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
	GPIO_Init(&GPIO_SPI);

	//MOSI
	GPIO_SPI.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
	GPIO_Init(&GPIO_SPI);
}

void SPI2_Init()
{
	/*
	 * Master mode
	 * Full duplex
	 * 2 Mhz (16Mhz/8)
	 * Data frame format 8 bit
	 * Serial clock polarity low
	 * Serial clock phase low
	 * Hardware slave select control (Software slave select management disable)
	 */
	SPI_Handle_t SPI2Hadle;

	SPI2Hadle.pSPIx = SPI2;
	SPI2Hadle.SPI_Config.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
	SPI2Hadle.SPI_Config.SPI_BusConfig = SPI_BUS_CNFG_FD;
	SPI2Hadle.SPI_Config.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV8;
	SPI2Hadle.SPI_Config.SPI_DFF = SPI_DFF_8BIT;
	SPI2Hadle.SPI_Config.SPI_CPOL= SPI_CPOL_LOW;
	SPI2Hadle.SPI_Config.SPI_CPHA = SPI_CPHA_LOW;
	SPI2Hadle.SPI_Config.SPI_SSM = SPI_SSM_DI;

	SPI_Init(&SPI2Hadle);
}

void GPIO_Button_Init()
{
	/*
	 * PA0 pin configure to trigger EXTI0 interrupt
	 */
	GPIO_Handle_t GPIO_Btn;

	GPIO_Btn.pGPIOx = GPIOA;

	GPIO_Btn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;
	GPIO_Btn.GPIO_PinConfig.GPIO_PuPdControl = GPIO_NO_PUPD;
	GPIO_Btn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;

	GPIO_Init(&GPIO_Btn);

	GPIO_IRQPriorityConfig(EXTI0_IRQn, NVIC_IRQ_PRI5);
	GPIO_IRQITConfig(EXTI0_IRQn, ENABLE);

}

void GPIO_LED_Init()
{
	/*
	*	PD12 and PD13 are connected user LEDs on discovery board
	*/
	GPIO_Handle_t GPIO_LED;

	GPIO_LED.pGPIOx = GPIOD;

	GPIO_LED.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GPIO_LED.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GPIO_LED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OP_SPEED_MEDIUM;
	GPIO_LED.GPIO_PinConfig.GPIO_PuPdControl = GPIO_NO_PUPD;
	GPIO_LED.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;

	GPIO_Init(&GPIO_LED);

	GPIO_LED.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;

	GPIO_Init(&GPIO_LED);
}

void GPIO_LED_IN_Init()
{
	/*
	* This function used to check slave LED out pin high or low
	* after COMMAND_LED_CTRL send to slave.
	*/
	GPIO_Handle_t GPIO_LED_IN;

	GPIO_LED_IN.pGPIOx = GPIOA;

	GPIO_LED_IN.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	GPIO_LED_IN.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OP_SPEED_HIGH;
	GPIO_LED_IN.GPIO_PinConfig.GPIO_PuPdControl = GPIO_PIN_PU;
	GPIO_LED_IN.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_3;

	GPIO_Init(&GPIO_LED_IN);

}
void Toggle_LED()
{
	//Toggle LED
	GPIO_Toggle_Pin(GPIOD, GPIO_PIN_NO_12);
	Delay(50000);
	GPIO_Toggle_Pin(GPIOD, GPIO_PIN_NO_12);
	Btn = RESET;
}

uint8_t SPI_VerifyResponse(uint8_t ackbyte)
{
	if(ackbyte == 0xf5)
		return 1;
	return 0;
}
int main(void)
{
	uint8_t dummy_byte = 0xFF;
	uint8_t dummy_read;
	uint8_t ackbyte;
	uint8_t args[2];
	uint8_t anlg_value,dgtl_value,Ardunio_ID;
	char user_data[] = "SPI driver test written by Eren";
	//SPI2 GPIO Configuration
	SPI2_GPIO_Init();

	//SPI2 Configuration
	SPI2_Init();

	//Enable NSS output
	SPI_SSOE_Config(SPI2, ENABLE);

	//GPIO Button Configuration
	GPIO_Button_Init();

	//GPIO LED Configuration
	GPIO_LED_Init();

	//GPIO Read pin
	GPIO_LED_IN_Init();

	while(1)
	{
		//Wait until button pressed
		while(! Btn);

		//Toggle LED and RESET Btn
		Toggle_LED();

		SPI_PeripheralControl(SPI2, ENABLE);

		//Send first Command
		uint8_t command = COMMAND_LED_CTRL;


		SPI_SendData(SPI2, &command, 1);

		//RXEN flag should be cleared so to clear the RXNE after every send some data must be received
		SPI_ReceiveData(SPI2, &dummy_read, 1);

		//Send some dummy bits to fetch the response from the slaves
		SPI_SendData(SPI2, &dummy_byte, 1);

		//Read the ack byte recieved
		SPI_ReceiveData(SPI2, &ackbyte, 1);

		if(SPI_VerifyResponse(ackbyte))
		{
			//send arguments
			args[0] = LED_PIN;
			args[1] = LED_ON;

			SPI_SendData(SPI2, args, 2);

			/*Check if slave LED_PIN is high or not.
			* If LED_PIN is high then set PD13(ORANGE LED)
			*/
			if(GPIO_Read_Pin(GPIOA, GPIO_PIN_NO_3))
			{
				GPIO_Write_Pin(GPIOD, GPIO_PIN_NO_13, SET);
			}
			else
			{
				GPIO_Write_Pin(GPIOD, GPIO_PIN_NO_13, RESET);
			}

		}

		//Wait until button pressed
		while(! Btn);

		//Toggle LED and RESET Btn
		Toggle_LED();

		//Send second Command
		command = COMMAND_SENSOR_READ;

		SPI_SendData(SPI2, &command, 1);

		//RXEN flag should be cleared so to clear the RXNE after every send some data must be received
		SPI_ReceiveData(SPI2, &dummy_read, 1);

		//Send some dummy bits to fetch the response from the slaves
		SPI_SendData(SPI2, &dummy_byte, 1);

		//Read the ack byte recieved
		SPI_ReceiveData(SPI2, &ackbyte, 1);

		if(SPI_VerifyResponse(ackbyte))
		{
			//send arguments
			args[0] = ANALOG_PIN0;

			SPI_SendData(SPI2, args, 1);

			//Wait so slave can read analog pin
			Delay(100);

			//Send some dummy bits to fetch the response from the slaves
			SPI_SendData(SPI2, &dummy_byte, 1);

			//Read the analog pin value recieved
			SPI_ReceiveData(SPI2, &anlg_value, 1);
		}

		//Wait until button pressed
		while(! Btn);

		//Toggle LED and RESET Btn
		Toggle_LED();

		//Send third Command
		command = COMMAND_PIN_READ;

		SPI_SendData(SPI2, &command, 1);

		//RXEN flag should be cleared so to clear the RXNE after every send some data must be received
		SPI_ReceiveData(SPI2, &dummy_read, 1);

		//Send some dummy bits to fetch the response from the slaves
		SPI_SendData(SPI2, &dummy_byte, 1);

		//Read the ack byte recieved
		SPI_ReceiveData(SPI2, &ackbyte, 1);

		if(SPI_VerifyResponse(ackbyte))
		{
			//send arguments
			args[0] = LED_PIN;

			SPI_SendData(SPI2, args, 1);

			//Wait so slave can read digital pin
			Delay(100);

			//Send some dummy bits to fetch the response from the slaves
			SPI_SendData(SPI2, &dummy_byte, 1);

			//Read the digital pin value recieved
			SPI_ReceiveData(SPI2, &dgtl_value, 1);
		}

		//Wait until button pressed
		while(! Btn);

		//Toggle LED and RESET Btn
		Toggle_LED();

		//Send fourth Command
		command = COMMAND_PRINT;

		SPI_SendData(SPI2, &command, 1);

		//RXEN flag should be cleared so to clear the RXNE after every send some data must be received
		SPI_ReceiveData(SPI2, &dummy_read, 1);

		//Send some dummy bits to fetch the response from the slaves
		SPI_SendData(SPI2, &dummy_byte, 1);

		//Read the ack byte recieved
		SPI_ReceiveData(SPI2, &ackbyte, 1);

		if(SPI_VerifyResponse(ackbyte))
		{
			//send arguments
			uint8_t data_len = strlen(user_data);

			SPI_SendData(SPI2, &data_len, 1);

			SPI_SendData(SPI2,(uint8_t*)user_data,strlen(user_data));

		}

		//Wait until button pressed
		while(! Btn);

		//Toggle LED and RESET Btn
		Toggle_LED();

		//Send fiveth Command
		command = COMMAND_ID_READ;

		SPI_SendData(SPI2, &command, 1);

		//RXEN flag should be cleared so to clear the RXNE after every send some data must be received
		SPI_ReceiveData(SPI2, &dummy_read, 1);

		//Send some dummy bits to fetch the response from the slaves
		SPI_SendData(SPI2, &dummy_byte, 1);

		//Read the ack byte recieved
		SPI_ReceiveData(SPI2, &ackbyte, 1);

		if(SPI_VerifyResponse(ackbyte))
		{
			//Send some dummy bits to fetch the response from the slaves
			SPI_SendData(SPI2, &dummy_byte, 1);

			//Read the Ardunio ID recieved
			SPI_ReceiveData(SPI2, &Ardunio_ID, 1);
		}
	}

}

void EXTI0_IRQHandler(void)
{
	//To avoid debouncing
	Delay(50000);

	//Clear the interrupt flag
	GPIO_IRQ_Handling(GPIO_PIN_NO_0);

	//Set global variable
	Btn = SET;

}
